<Narkis>

    GridLayout:
        col: 2
        size: root.width, root.height

        BoxLayout:
            orientation: 'vertical'
            size: root.width, root.height

            padding: 50
            spacing: 20

            Button:
                text: "Scan Ebay"
            Button:
                text: "Edit Table"

        Button:
            size: 50, 100
            text: "Edit Table"



