# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1800, 1600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("   background-color: rgb(74, 74, 74)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(0, -1, 0, 700)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scanEbay_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scanEbay_btn.sizePolicy().hasHeightForWidth())
        self.scanEbay_btn.setSizePolicy(sizePolicy)
        self.scanEbay_btn.setMinimumSize(QtCore.QSize(300, 50))
        self.scanEbay_btn.setMaximumSize(QtCore.QSize(600, 100))
        self.scanEbay_btn.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    background-color: rgb(77, 77, 77);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    text-color: white;\n"
"    border-color: rgb(85, 255, 255);\n"
"    font: bold 30px;\n"
"    padding: 6px;\n"
" }QPushButton:hover {\n"
"      background-color: rgb(148, 148, 148);\n"
" }")
        self.scanEbay_btn.setObjectName("scanEbay_btn")
        self.verticalLayout.addWidget(self.scanEbay_btn)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setMinimumSize(QtCore.QSize(300, 2))
        self.line_3.setMaximumSize(QtCore.QSize(600, 4))
        self.line_3.setStyleSheet("\n"
" background-color: rgb(77, 77, 77);\n"
"")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.editTable_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editTable_btn.sizePolicy().hasHeightForWidth())
        self.editTable_btn.setSizePolicy(sizePolicy)
        self.editTable_btn.setMinimumSize(QtCore.QSize(300, 50))
        self.editTable_btn.setMaximumSize(QtCore.QSize(600, 100))
        self.editTable_btn.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    background-color: rgb(77, 77, 77);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    text-color: white;\n"
"    border-color: rgb(85, 255, 255);\n"
"    font: bold 30px;\n"
"    padding: 6px;\n"
" }QPushButton:hover {\n"
"      background-color: rgb(148, 148, 148);\n"
" }")
        self.editTable_btn.setObjectName("editTable_btn")
        self.verticalLayout.addWidget(self.editTable_btn)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setMinimumSize(QtCore.QSize(300, 2))
        self.line_2.setMaximumSize(QtCore.QSize(600, 4))
        self.line_2.setStyleSheet("\n"
" background-color: rgb(77, 77, 77);\n"
"")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.bid_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bid_btn.sizePolicy().hasHeightForWidth())
        self.bid_btn.setSizePolicy(sizePolicy)
        self.bid_btn.setMinimumSize(QtCore.QSize(300, 50))
        self.bid_btn.setMaximumSize(QtCore.QSize(600, 100))
        self.bid_btn.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    background-color: rgb(77, 77, 77);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    text-color: white;\n"
"    border-color: rgb(85, 255, 255);\n"
"    font: bold 30px;\n"
"    padding: 6px;\n"
" }QPushButton:hover {\n"
"      background-color: rgb(148, 148, 148);\n"
" }")
        self.bid_btn.setObjectName("bid_btn")
        self.verticalLayout.addWidget(self.bid_btn)
        self.line = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(300, 2))
        self.line.setMaximumSize(QtCore.QSize(600, 4))
        self.line.setStyleSheet("\n"
" background-color: rgb(77, 77, 77);\n"
"")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.veroChecker_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.veroChecker_btn.sizePolicy().hasHeightForWidth())
        self.veroChecker_btn.setSizePolicy(sizePolicy)
        self.veroChecker_btn.setMinimumSize(QtCore.QSize(300, 50))
        self.veroChecker_btn.setMaximumSize(QtCore.QSize(600, 100))
        self.veroChecker_btn.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    background-color: rgb(77, 77, 77);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    text-color: white;\n"
"    border-color: rgb(85, 255, 255);\n"
"    font: bold 30px;\n"
"    padding: 6px;\n"
" }QPushButton:hover {\n"
"      background-color: rgb(148, 148, 148);\n"
" }")
        self.veroChecker_btn.setObjectName("veroChecker_btn")
        self.verticalLayout.addWidget(self.veroChecker_btn)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setMinimumSize(QtCore.QSize(300, 2))
        self.line_4.setMaximumSize(QtCore.QSize(600, 4))
        self.line_4.setStyleSheet("\n"
" background-color: rgb(77, 77, 77);\n"
"")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("QLabel{\n"
"    text-decoration: underline;\n"
"text-decoration-style: double;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.dataWind = QtWidgets.QVBoxLayout()
        self.dataWind.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.dataWind.setContentsMargins(0, -1, 0, -1)
        self.dataWind.setObjectName("dataWind")
        self.horizontalLayout.addLayout(self.dataWind)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Narkis 3.0"))
        self.scanEbay_btn.setText(_translate("MainWindow", "Scan Ebay"))
        self.editTable_btn.setText(_translate("MainWindow", "Edit Table"))
        self.bid_btn.setText(_translate("MainWindow", "Bid "))
        self.veroChecker_btn.setText(_translate("MainWindow", "VeRO Checker"))
        self.label.setText(_translate("MainWindow", "Narkis Version 3.0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
